FROM alpine

ENV VERSION 0.12.0
ENV IS_SERVER true
#frps.ini
ENV BIND_PORT 7000
ENV VHOST_HTTP_PORT 8080
ENV VHOST_HTTPS_PORT 8443
ENV DASHBOARD_PORT 7500
ENV DASHBOARD_USER admin
ENV DASHBOARD_PWD zwise
ENV LOG_FILE ./frp.log
ENV LOG_LEVEL info
ENV LOG_MAX_DAYS 7
ENV PRIVILEGE_TOKEN zwise
ENV MAX_POOL_COUNT 10
ENV AUTHENTICATION_TIMEOUT 120
ENV SUBDOMAIN_HOST zwise.pw
#frpc.ini
ENV SERVER_ADDR 119.29.185.237
ENV POOL_COUNT 1
ENV SSH_LOCAL_IP 127.0.0.1
ENV SSH_LOCAL_PORT 22
ENV SSH_REMOTE_PORT 2222
ENV WEB01_TYPE https
ENV WEB01_LOCAL_PORT 443
ENV WEB01_SUBDOMAIN nas
ENV WEB02_TYPE http
ENV WEB02_LOCAL_PORT 80
ENV WEB02_SUBDOMAIN www

WORKDIR /root

ADD https://github.com/fatedier/frp/releases/download/v${VERSION}/frp_${VERSION}_linux_amd64.tar.gz .

RUN set -xe \
    && tar zxf frp_${VERSION}_linux_amd64.tar.gz \
    && rm frp_${VERSION}_linux_amd64.tar.gz

ADD ./entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

EXPOSE 7000 7500 2222 8080 8443

ENTRYPOINT ["/entrypoint.sh"]
